"""
Jira & GitHub Issues Integration Module
Handles bi-directional sync and converts task graph action items into tracked software engineering tickets.
"""
from typing import Dict, List, Any

class JiraGitHubSync:
    @staticmethod
    def format_jira_issue(task: Dict[str, Any], project_key: str = "PROJ") -> Dict[str, Any]:
        priority_map = {"CRITICAL": "Highest", "HIGH": "High", "MEDIUM": "Medium", "LOW": "Low"}
        return {
            "fields": {
                "project": {"key": project_key},
                "summary": task.get("title"),
                "description": f"Automated Task extracted from AI Meeting Intelligence.\nOrigin Meeting: {task.get('meetingId')}\nDependencies: {', '.join(task.get('dependsOn', []))}",
                "issuetype": {"name": "Task"},
                "priority": {"name": priority_map.get(task.get("priority", "MEDIUM"), "Medium")},
                "duedate": task.get("deadline", "").split()[0] if task.get("deadline") else None,
                "labels": ["ai-meeting-intelligence", f"meeting-{task.get('meetingId')}"]
            }
        }

    @staticmethod
    def format_github_issue(task: Dict[str, Any]) -> Dict[str, Any]:
        return {
            "title": task.get("title"),
            "body": f"### 🤖 Action Item from Meeting `{task.get('meetingId')}`\n\n**Owner:** `@{task.get('owner')}`\n**Deadline:** `{task.get('deadline')}`\n**Priority:** `{task.get('priority')}`\n\n_Auto-generated by AI Meeting Intelligence_",
            "labels": ["action-item", f"priority:{task.get('priority', 'medium').lower()}"],
            "assignees": [task.get("owner", "").lower()] if task.get("owner") else []
        }
